apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Integration
metadata:
  annotations:
    meta.upbound.io/example-id: apigatewayv2/v1beta1/integration
  labels:
    upjet.upbound.io/test-group: apigatewayv2-http
  name: crossplane-integration
spec:
  forProvider:
    apiIdSelector:
      matchLabels:
        upjet.upbound.io/test-group: apigatewayv2-http
    integrationMethod: POST
    integrationType: AWS_PROXY
    integrationUri: https://api.example.com
    region: us-east-1
